from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[2]


# Data
DATA_DIR = ROOT_DIR / "data"

RAW_DIR = DATA_DIR / "raw"
DATABASE_DIR = DATA_DIR / "database"
RESULTS_DIR = DATA_DIR / "results"


# Normalized databases
DISTRIBUTIONS_DATABASE = DATABASE_DIR / "distributions.xlsx"
EXPERIMENTS_DATABASE = DATABASE_DIR / "experiments.xlsx"
OIL_PROPERTIES_DATABASE = DATABASE_DIR / "oil_properties.xlsx"


# External data
OIL_EXTERNAL_PROPERTIES = RAW_DIR / "oil_external_properties.xlsx"

REFERENCE_DIR = DATA_DIR / "reference"

OIL_REFERENCE_PATH = REFERENCE_DIR / "oils.csv"

OIL_DETAILED_PROPERTIES_DIR = RAW_DIR / "oil_detailed_properties"


# Shared figures
FIGURES_DIR = RESULTS_DIR / "figures"

# Distribution modelling
DISTRIBUTION_RESULTS_DIR = RESULTS_DIR / "distributions"

DISTRIBUTION_REFERENCE_DIR = DISTRIBUTION_RESULTS_DIR / "reference"

DISTRIBUTION_REFERENCE_FIGURES_DIR = DISTRIBUTION_REFERENCE_DIR / "figures"

DISTRIBUTION_PARAMETERS_PATH = DISTRIBUTION_RESULTS_DIR / "parameters.xlsx"

DISTRIBUTION_ANALYSIS_DIR = DISTRIBUTION_RESULTS_DIR / "analysis"

DISTRIBUTION_FIT_EVALUATION_PATH = DISTRIBUTION_ANALYSIS_DIR / "fit_evaluation.xlsx"

DISTRIBUTION_METHOD_COMPARISON_PATH = (
    DISTRIBUTION_ANALYSIS_DIR / "method_comparison.xlsx"
)

DISTRIBUTION_ANALYSIS_FIGURES_DIR = DISTRIBUTION_ANALYSIS_DIR / "figures"

DISTRIBUTION_PARAMETER_ANALYSIS_DIR = DISTRIBUTION_ANALYSIS_DIR / "parameters"

DISTRIBUTION_PARAMETER_FIGURES_DIR = DISTRIBUTION_PARAMETER_ANALYSIS_DIR / "figures"

DISTRIBUTION_SCALE_EFFECT_DIR = DISTRIBUTION_ANALYSIS_DIR / "scale_effect"

DISTRIBUTION_SCALE_EFFECT_FIGURES_DIR = DISTRIBUTION_SCALE_EFFECT_DIR / "figures"

DISTRIBUTION_CORRELATION_ANALYSIS_DIR = DISTRIBUTION_ANALYSIS_DIR / "correlation"

DISTRIBUTION_CORRELATION_FIGURES_DIR = DISTRIBUTION_CORRELATION_ANALYSIS_DIR / "figures"

# Experimental analysis
EXPERIMENTAL_RESULTS_DIR = RESULTS_DIR / "experimental"

EXPERIMENTAL_SUMMARY_DIR = EXPERIMENTAL_RESULTS_DIR / "summary"
EXPERIMENTAL_SUMMARY_FIGURES_DIR = EXPERIMENTAL_SUMMARY_DIR / "figures"

EXPERIMENTAL_SSDI_DIR = EXPERIMENTAL_RESULTS_DIR / "ssdi"
EXPERIMENTAL_SSDI_FIGURES_DIR = EXPERIMENTAL_SSDI_DIR / "figures"

EXPERIMENTAL_SSMD_DIR = EXPERIMENTAL_RESULTS_DIR / "ssmd"
EXPERIMENTAL_SSMD_FIGURES_DIR = EXPERIMENTAL_SSMD_DIR / "figures"

EXPERIMENTAL_TREATMENT_EFFECT_DIR = EXPERIMENTAL_RESULTS_DIR / "treatment_effect"

EXPERIMENTAL_TREATMENT_EFFECT_FIGURES_DIR = (
    EXPERIMENTAL_TREATMENT_EFFECT_DIR / "figures"
)


# SSDI
SSDI_RESULTS_DIR = RESULTS_DIR / "ssdi"

SSDI_PREDICTIONS_PATH = SSDI_RESULTS_DIR / "predictions.xlsx"

SSDI_CALIBRATIONS_PATH = SSDI_RESULTS_DIR / "calibrations.xlsx"


# SSDI performance
SSDI_PERFORMANCE_DIR = SSDI_RESULTS_DIR / "performance"

SSDI_PERFORMANCE_RESULTS_PATH = SSDI_PERFORMANCE_DIR / "results.xlsx"

SSDI_PERFORMANCE_FIGURES_DIR = SSDI_PERFORMANCE_DIR / "figures"


# SSDI sensitivity analysis
SSDI_SENSITIVITY_DIR = SSDI_RESULTS_DIR / "sensitivity"

SSDI_SENSITIVITY_RESULTS_PATH = SSDI_SENSITIVITY_DIR / "results.xlsx"

SSDI_SENSITIVITY_FIGURES_DIR = SSDI_SENSITIVITY_DIR / "figures"


# SSDI oil-wise calibration
SSDI_OIL_WISE_DIR = SSDI_RESULTS_DIR / "oil_wise"

SSDI_OIL_WISE_RESULTS_PATH = SSDI_OIL_WISE_DIR / "results.xlsx"

SSDI_OIL_WISE_FIGURES_DIR = SSDI_OIL_WISE_DIR / "figures"


# SSDI predictive validation
SSDI_VALIDATION_DIR = SSDI_RESULTS_DIR / "validation"

SSDI_VALIDATION_RESULTS_PATH = SSDI_VALIDATION_DIR / "results.xlsx"

SSDI_VALIDATION_FIGURES_DIR = SSDI_VALIDATION_DIR / "figures"


# SSDI model comparison
SSDI_COMPARISON_DIR = SSDI_RESULTS_DIR / "comparison"

SSDI_COMPARISON_RESULTS_PATH = SSDI_COMPARISON_DIR / "results.xlsx"

SSDI_COMPARISON_FIGURES_DIR = SSDI_COMPARISON_DIR / "figures"


# SSMD
SSMD_RESULTS_DIR = RESULTS_DIR / "ssmd"

SSMD_PREDICTIONS_PATH = SSMD_RESULTS_DIR / "predictions.xlsx"

SSMD_CALIBRATIONS_PATH = SSMD_RESULTS_DIR / "calibrations.xlsx"


# SSMD performance
SSMD_PERFORMANCE_DIR = SSMD_RESULTS_DIR / "performance"

SSMD_PERFORMANCE_RESULTS_PATH = SSMD_PERFORMANCE_DIR / "results.xlsx"

SSMD_PERFORMANCE_FIGURES_DIR = SSMD_PERFORMANCE_DIR / "figures"


# SSMD oil-wise analysis
SSMD_OIL_WISE_DIR = SSMD_RESULTS_DIR / "oil_wise"

SSMD_OIL_WISE_RESULTS_PATH = SSMD_OIL_WISE_DIR / "results.xlsx"

SSMD_OIL_WISE_FIGURES_DIR = SSMD_OIL_WISE_DIR / "figures"


# SSMD predictive validation
SSMD_VALIDATION_DIR = SSMD_RESULTS_DIR / "validation"

SSMD_VALIDATION_RESULTS_PATH = SSMD_VALIDATION_DIR / "results.xlsx"

SSMD_VALIDATION_FIGURES_DIR = SSMD_VALIDATION_DIR / "figures"
