from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[2]

DATA_DIR = ROOT_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
DATABASE_DIR = DATA_DIR / "database"
RESULTS_DIR = DATA_DIR / "results"

FIGURES_DIR = RESULTS_DIR / "figures"

SSDI_FIGURES_DIR = FIGURES_DIR / "ssdi"
SSMD_FIGURES_DIR = FIGURES_DIR / "ssmd"
DISTRIBUTION_FIGURES_DIR = FIGURES_DIR / "distributions"

EXPERIMENTAL_FIGURES_DIR = FIGURES_DIR / "experimental"
EXPERIMENTAL_SUMMARY_FIGURES_DIR = EXPERIMENTAL_FIGURES_DIR / "summary"
EXPERIMENTAL_SSDI_FIGURES_DIR = EXPERIMENTAL_FIGURES_DIR / "ssdi"
EXPERIMENTAL_SSMD_FIGURES_DIR = EXPERIMENTAL_FIGURES_DIR / "ssmd"
EXPERIMENTAL_TREATMENT_EFFECT_FIGURES_DIR = (
    EXPERIMENTAL_FIGURES_DIR / "treatment_effect"
)

DISTRIBUTIONS_DATABASE = DATABASE_DIR / "distributions.xlsx"
EXPERIMENTS_DATABASE = DATABASE_DIR / "experiments.xlsx"
OIL_PROPERTIES_DATABASE = DATABASE_DIR / "oil_properties.xlsx"

OIL_EXTERNAL_PROPERTIES = RAW_DIR / "oil_external_properties.xlsx"

SSDI_RESULTS = RESULTS_DIR / "ssdi_results.xlsx"
SSMD_RESULTS = RESULTS_DIR / "ssmd_results.xlsx"
